# Generated by Django 5.0.2 on 2024-02-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantedtree',
            options={'ordering': ('-planted_at',)},
        ),
    ]
