# Generated by Django 5.0.2 on 2024-02-19 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_plantedtree_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-joined',)},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ('-scientific_name',)},
        ),
        migrations.AlterField(
            model_name='plantedtree',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planted_trees_tree', to='trees.tree'),
        ),
    ]
